// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cyInwEww4aM80dxNz2ynHwrFU_6Fvus',
    appId: '1:1059831909262:web:64b37bb4c6157ed1a0b2df',
    messagingSenderId: '1059831909262',
    projectId: 'chatapp-f74ff',
    authDomain: 'chatapp-f74ff.firebaseapp.com',
    storageBucket: 'chatapp-f74ff.appspot.com',
    measurementId: 'G-NS74QRV217',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYMu2GfSP0nna61Czyn5DjSf0FxnGkPos',
    appId: '1:1059831909262:android:e75afaa742da1305a0b2df',
    messagingSenderId: '1059831909262',
    projectId: 'chatapp-f74ff',
    storageBucket: 'chatapp-f74ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9JhbvnBB4BNNStwFGQ-HCfPcL4IBu-5w',
    appId: '1:1059831909262:ios:7b3766afcceb477da0b2df',
    messagingSenderId: '1059831909262',
    projectId: 'chatapp-f74ff',
    storageBucket: 'chatapp-f74ff.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9JhbvnBB4BNNStwFGQ-HCfPcL4IBu-5w',
    appId: '1:1059831909262:ios:7b3766afcceb477da0b2df',
    messagingSenderId: '1059831909262',
    projectId: 'chatapp-f74ff',
    storageBucket: 'chatapp-f74ff.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3cyInwEww4aM80dxNz2ynHwrFU_6Fvus',
    appId: '1:1059831909262:web:40ae5eb2cad5b7d8a0b2df',
    messagingSenderId: '1059831909262',
    projectId: 'chatapp-f74ff',
    authDomain: 'chatapp-f74ff.firebaseapp.com',
    storageBucket: 'chatapp-f74ff.appspot.com',
    measurementId: 'G-2TPBY58WWF',
  );
}
